Fix pint issue
dgbowl/dgpost pull request #94
Opened 2024-08-30 15:06 UTC by NukP

This PR is made in respond to Issue #92 
I have remove the definition of Refractive index from dgpost as suggested.
I have tested this and it now works just fine (can now process the data like before)

2024-08-30 18:56 UTC, PeterKraus requested changes

2024-08-30 18:56 UTC, PeterKraus commented on tests/__init__.py
> +#Random comment
Please revert those changes.

2024-08-30 18:56 UTC, PeterKraus commented on tests/test_catalysis_atbal.py
> +    assert np.allclose(df["O2"], pd.DataFrame([1.0, 1.0, 0.95, 1.05, 1.0, 1.0]))
Please revert those changes, too.

2024-09-02 08:58 UTC, NukP commented
I have rebased the brach so that those commits have been reverted from this PR as requested.

2024-09-02 18:03 UTC, PeterKraus approved these changes
I bumped the minimum version of `pint` to `>=0.24.1`. The RIU were introduced into `pint` in `0.24`, but that one is not compatible with `python==3.9`, so it's better to ask for `0.24.1` and above.

2024-09-02 18:04 UTC, merged